from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent

# Tank interlock
USE_LEVEL_SENSOR_FOR_AUTONOMY = False
LEVEL_SENSOR_GPIO = 17
LEVEL_SENSOR_WATER_ACTIVE_LOW = True
EMPTY_CONFIRM_TIME = 3.0
WATER_RECOVERY_TIME = 2.0

# Spray rail
SERVO_GPIO = 18
HORIZONTAL_ANGLE = 87.0
VERTICAL_ANGLE = 0.0
SERVO_MIN_PULSE_WIDTH = 0.0005
SERVO_MAX_PULSE_WIDTH = 0.0025
SERVO_SETTLE_TIME = 0.60

# Pump relay
PUMP_RELAY_GPIO = 23
PUMP_RELAY_ACTIVE_LOW = False

# ESP32 UART
ESP_SERIAL_PORT = "/dev/ttyAMA0"
ESP_BAUD_RATE = 115200
ESP_HEARTBEAT_INTERVAL = 0.25
ESP_PEER_ALIVE_TIMEOUT = 1.25
ESP_RECONNECT_INTERVAL = 1.0
ESP_WORKER_POLL_INTERVAL = 0.005

# Pi LiDAR copy
LIDAR_VISUALIZATION_ENABLED = True
LIDAR_SERIAL_PORT = "/dev/ttyAMA2"
LIDAR_BAUD_RATE = 230400
LIDAR_PACKET_LENGTH = 47
LIDAR_POINTS_PER_PACKET = 12
LIDAR_DATA_TIMEOUT = 0.75
LIDAR_POINT_MAX_AGE = 0.60
LIDAR_MAX_DISTANCE_MM = 6000
LIDAR_MAX_UI_POINTS = 72
LIDAR_UI_INTERVAL = 0.50

# Detector
MODEL_PATH = PROJECT_DIR / "models" / "weednano.pt"
DETECTION_CONFIDENCE = 0.25
DETECTION_IMAGE_SIZE = 640
CAMERA_SIZE = (640, 480)
JPEG_QUALITY = 72
YOLO_CPU_THREADS = 3
CAMERA_WARMUP_TIME = 1.5
DETECTOR_STOP_TIMEOUT = 3.0

# Automatic spraying
SPRAY_CONFIDENCE = 0.45
DETECTION_STALE_TIME = 0.75
SPRAY_SUPERVISOR_INTERVAL = 0.05

TARGET_LABELS = {
    "weed": {"weed", "weeds"},
    "maize": {"maize", "corn"},
}

# App communication
TELEMETRY_INTERVAL = 0.50

# Route storage
ROUTE_DATA_DIR = Path.home() / "weed_data"
ROUTE_DB_PATH = ROUTE_DATA_DIR / "routes.db"

DEFAULT_FIELD_WIDTH_CM = 400.0
DEFAULT_FIELD_HEIGHT_CM = 400.0
DEFAULT_ROW_COUNT = 2

SEED_DEMO_ROUTE = False
